services:
  worker:
    image: activity-relay:local
    build: &relay-build
      context: .
      args:
        VERSION: ${ACTIVITY_RELAY_VERSION:-development}

  server:
    image: activity-relay:local
    build: *relay-build
