bind 127.0.0.1 -::1
protected-mode yes
port 6380
tcp-backlog 128
timeout 0
tcp-keepalive 300
daemonize no
supervised systemd
loglevel notice
logfile ""
databases 1
dir /var/lib/activity-relay/redis
dbfilename dump.rdb
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
appendonly no
maxmemory 512mb
maxmemory-policy noeviction
